name: Move Linked Issue to Done When PR Merged

on:
  pull_request:
    types: [closed]

jobs:
  move_item:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Move card to Done
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          project-url: https://github.com/users/MANISHIMWEPacifique/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
          status: "Done"
          resource-node-id: ${{ github.event.pull_request.node_id }}
